"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TextSplitterStream = exports.KittenTTS = exports.detectWebGPU = exports.cleanTextForTTS = exports.chunkText = void 0;
const kitten_tts_1 = require("./lib/kitten-tts");
Object.defineProperty(exports, "KittenTTS", { enumerable: true, get: function () { return kitten_tts_1.KittenTTS; } });
const text_cleaner_1 = require("./utils/text-cleaner");
Object.defineProperty(exports, "chunkText", { enumerable: true, get: function () { return text_cleaner_1.chunkText; } });
Object.defineProperty(exports, "cleanTextForTTS", { enumerable: true, get: function () { return text_cleaner_1.cleanTextForTTS; } });
const utils_1 = require("./utils/utils");
Object.defineProperty(exports, "detectWebGPU", { enumerable: true, get: function () { return utils_1.detectWebGPU; } });
Object.defineProperty(exports, "TextSplitterStream", { enumerable: true, get: function () { return utils_1.TextSplitterStream; } });
